### ISSUE TITLE
Klausimas

### ISSUE THREAD

**Issue by d00maz** [ntacamp/404.notrollsallowed.com#238]
Labas, uzklydau i ntacamp , labai patiko kad tokios temos susiburimai vyksta, ar yra koks faq kaip butu galima sudalyvauti prijauciantiems ?
Is anksto aciu.

**Comment by Pawka** [comment]
Labas. Renginys yra tik su pakvietimais. FAQ perduodamas iš lūpų į lūpas. Jei pažįsti kas dalyvavo - paprašyk, kad papasakotų taisykles. Stengiamės, kad nebūtų netyčia užklydusių :-) Smagu, kad domiesi ir ačiū už supratimą.
