### ISSUE TITLE
Ar vienas trolis šiais metais leidžiamas?

### ISSUE THREAD

**Issue by p12tic** [ntacamp/404.notrollsallowed.com#33]
404.txt sako: "If you want to participate, you must contribute." Neaišku, ar galima kartu pasiimti 1 trolį kaip ir per praėjusius NTA. Siūlau pakeisti į kažkurį iš šių:

    If you want to participate, you must contribute. No trolls allowed this year.

Arba:

    If you want to participate, you must contribute. You can bring one troll together with you.

**Comment by Pawka** [comment]
Žinantiems taisykles - jos tokios pačios kaip visada ;-)
